#
# Verifica validità organizationId
x-commons:
  ratelimit-headers: &ratelimit-headers
    X-RateLimit-Limit:
      $ref: '#/components/headers/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: '#/components/headers/X-RateLimit-Remaining'
    X-RateLimit-Reset:
        $ref: '#/components/headers/X-RateLimit-Reset'
  common-responses: &common-responses
    '400':
      $ref: '#/components/responses/400BadRequest'
    '401':
      $ref: '#/components/responses/401Unauthorized'
    '429':
      $ref: '#/components/responses/429TooManyRequests'
    '500':
      $ref: '#/components/responses/500InternalServerError'
    default:
      $ref: '#/components/responses/default'


    
openapi: 3.0.1
info:
  version: "3.0.0"
  termsOfService: https://www.agenziaentrate.gov.it/portale/web/guest/privacy
  title: |-
    Verifica validità organizationId.
  x-summary: >-
    Verifica di validità di un organizationId e recupero di alcuni dati anagrafici

  description: |
    #### Documentazione
    Questo servizio ritorna la validità di un organizationId. In caso riscontro positivo 
    vengono fornite alcune informazioni di tipo
    anagrafico tra cui eventuali riferimenti al GRUPPO IVA:

    - STATO, DENOMINAZIONE, DATA INIZIO ATTIVITA', DATA CESSAZIONE, DATA SOSPENSIONE
    
    ##### Denominazione
    Per le ditte individuali viene fornita la denominazione se dichiarata, diversamente il cognome e nome del titolare

    ##### Gruppo Iva
    Il concetto di *GRUPPO IVA* può essere approfondito al seguente
    [link](https://www.agenziaentrate.gov.it/portale/web/guest/schede/istanze/costituzione-gruppo-iva/scheda-informativa-costituzione-gruppoiva).
    
    #### Note
    Poiché il servizio effettua una verifica sul dato in input una risposta verrà sempre ritornata con stato 200 
    anche se l organizationId  in input non fosse presente negli archivi.
    
    Alcune "DATE" potrebbero essere espresse nei seguenti formati '1001-01-01', '9999-12-31'.
    Tali date devono essere interpretate come informazioni assenti o non certe.
    E' in corso una revisione degli archivi dell'Agenzia Delle Entrate per sanare queste informazioni.

    Il servizio non richiede autenticazione, ma va' usato rispettando gli
    header di throttling esposti in conformita' alle Linee Guida del Modello di interoperabilita'.
    
    ##### Confomrmità con il modello di interoperabilità
    L'Header di Throttling X-RateLimit-Reset non viene inviato in caso di https status code 200, sarà presente solo in caso di 429

    #### Sicurezza
    Pur essendo questa API di pubblico accesso, è richiesto l'invio delle API Key che consentono all'infrastruttura
    di applicare le politiche di throttling definite nell'ambito del piano sottoscritto
 
  
  contact:
    name: Agenzia delle Entrate
    url: https://www.agenziaentrate.gov.it
  x-audience:
    - public
  x-api-id: 5ca54741-8f62-4aad-ab79-13ae762920e3
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: public
    description: |-
      Endpoint non autenticato per la verifica dello stato del servizio
  - name: verifiche
    description: |-
      verifica la validità e l'esistenza della partita iva in input
    externalDocs:
      url: https://developer.agenziaentrate.gov.it/entrate/api
servers:
  - description: Ambiente di Attestazione
    url: https://mtls.eservices.att.interop.pagopa.it/


paths:
  /organizationid-verification/data-preparation/handshake:
    post:
      summary: Carica il certificato e i campi dell'header.
      description: Carica il certificato nel formato .pem insieme a due campi nell'header.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                certificate:
                  type: string
                  format: binary
                  description: Il certificato nel formato .pem
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
          description: Chiave dell'API
      responses:
        '200':
          description: Operazione completata con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di conferma dell'operazione
        '400':
          $ref: '#/components/responses/400BadRequest'
      tags:
        - datapreparation
  /organizationid-verification/data-preparation:
    post:
      summary: data preparation api.
      description: Carica i casi d'uso dell'ente
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatapreparationTemplate'
            examples:
              organizationIdAlfanumerico:
                value:
                  organizationId: 'AAAZZZ00H00T000Z'
              organizationIdNumerico:
                value:
                  organizationId: '06363391001'
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
          description: Chiave dell'API
        - in: header
          name: x-correlation-id
          required: true
          schema:
            type: string
          description: correlationId
      responses:
        '200':
          description: Operazione completata con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di conferma dell'operazione
        '400':
          $ref: '#/components/responses/400BadRequest'
      tags:
        - datapreparation
    get:
      summary: data preparation api.
      description: Lista dei casi d'uso dell'ente
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
          description: Chiave dell'API
        - in: header
          name: x-correlation-id
          required: true
          schema:
            type: string
          description: correlationId
      responses:
        '200':
          description: Operazione completata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPreparationResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
      tags:
        - datapreparation
    delete:
      summary: Cancella i casi d'uso dell'ente
      description: |
        Ritorna lo stato dell'applicazione: 200 se funziona correttamente
        o un errore se l'applicazione è temporaneamente indisponibile
        per manutenzione o per un problema tecnico.
      operationId: reset
      tags:
        - datapreparation
      responses:
        <<: *common-responses
        '200':
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          headers:
            <<: *ratelimit-headers
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /organizationid-verification/data-preparation/remove:
    post:
      summary: data preparation api.
      description: Rimuove un preciso caso d'uso
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatapreparationTemplate'
            examples:
              organizationIdAlfanumerico:
                value:
                  organizationId: 'AAAZZZ00H00T000Z'
              organizationIdNumerico:
                value:
                  organizationId: '06363391001'
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
          description: Chiave dell'API
        - in: header
          name: x-correlation-id
          required: true
          schema:
            type: string
          description: correlationId
      responses:
        '200':
          description: Operazione completata con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di conferma dell'operazione
        '400':
          $ref: '#/components/responses/400BadRequest'
      tags:
        - datapreparation
  /organizationid-verification/status:
    get:
      summary: Ritorna lo stato dell'applicazione.
      description: |
        Ritorna lo stato dell'applicazione: 200 se funziona correttamente
        o un errore se l'applicazione è temporaneamente indisponibile
        per manutenzione o per un problema tecnico.
      operationId: get_status
      tags:
        - public
      responses:
        '200':
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /organizationid-verification/verifica:
    post:
      summary: Valida un organizationId.
      description: |
        Ritorna informazioni sulla validità dell organizationId
        e in caso di esito positivo vengono aggiunte alcune informazioni anagrafiche.

      operationId: post_partita_organizationId
      tags:
        - verifiche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Richiesta'
            examples:
              organizationIdNumeric0:
                value:
                  organizationId: '06363391001'
      responses:
        <<: *common-responses
        '200':
          description: |
            Il servizio ha ritornato l'esito della validazione - che può essere positivo o negativo -
            a seconda del valore del campo `valida`.

            Attenzione! Le organizationId valide possono essere o meno attive: va quindi sempre
            verificato il contenuto della response.
          # header di throttling sono obbligatori
                      
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificaOrganizationId'
              examples:    # Esempi per ogni casistica
                Invalida:
                  value:
                    organizationId: '01043931007'
                    valida: false
                Attiva:
                  value:  &example_organizationId
                    organizationId: '06363391001'
                    valida: true
                    stato: 'ATTIVA'
                    denominazione: 'AGENZIA DELLE ENTRATE'
                    dataInizioAttivita: '2001-01-02'
                Sospesa:
                  value:
                    <<: *example_organizationId
                    stato: 'SOSPESA'
                    dataInizioSospensione: '2013-03-15'
                Cessata:
                  value:
                    <<: *example_organizationId
                    stato: 'CESSATA'
                    dataCessazioneAttivita: '1989-01-01'
                GruppoIva:
                  value:
                    <<: *example_organizationId
                    isGruppoIva: true
                PartecipanteGruppoIva:
                  value:
                    <<: *example_organizationId
                    isPartecipanteGruppoIva: true
                    dataInizioPartecipazioneGruppoIva: '2018-10-27'
                    partitaIvaGruppo: '06363391001'

components:
  schemas:

    DatapreparationTemplate:
      type: object
      properties:
        organizationId:
          $ref: '#/components/schemas/OrganizationId'

    DataPreparationResponse:
      type: array
      items:
        type: object
        properties:
          organizationId:
            $ref: '#/components/schemas/OrganizationId'

    Richiesta:
      type: object
      properties:
        organizationId:
          $ref: '#/components/schemas/OrganizationId'
    OrganizationId:
      type: string
      maxLength: 11
      minLength: 11
      pattern: '^[0-9]+'
      example: '06363391001'

    VerificaOrganizationId:
      type: object
      properties:
        organizationId:
          $ref: '#/components/schemas/OrganizationId'
        valida:
          type: boolean
          example: true
        stato:
          type: string
          enum:
            - ATTIVA
            - CESSATA
            - SOSPESA
          example: 'ATTIVA'
        denominazione:
          type: string
          example: 'AGENZIA DELLE ENTRATE'
        dataInizioAttivita:
          type: string
          format: date
          example: '1982-05-22'
        dataCessazioneAttivita:
          type: string
          format: date
          example: '1982-05-22'
        dataInizioSospensione:
          type: string
          format: date
          example: '1982-05-22'
        isGruppoIva:
          type: boolean
          example: false
        partitaIvaGruppo:
          $ref: '#/components/schemas/OrganizationId'
        dataInizioPartecipazioneGruppoIva:
          type: string
          format: date
          example: '1982-05-22'
        isPartecipanteGruppoIva:
          type: boolean
          example: false
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem. You MUST NOT expose internal informations, personal
            data or implementation details through this field.
          example: Request took too long to complete.
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          format: uri
          type: string
      type: object


  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        type: string
    WWW-Authenticate:
      description: |-
        Auth realm=APIkey
        See https://tools.ietf.org/html/rfc7235#section-4.1
      schema:
        type: string
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: string
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        type: string
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        type: string

  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Bad Request
    401Unauthorized:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      headers:
        WWW-Authenticate:
          $ref: '#/components/headers/WWW-Authenticate'
      description: Not authorized
    403Forbidden:
      description: Forbidden
    404NotFound:
      description: Not Found
    429TooManyRequests:
      description: Too many requests
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
    500InternalServerError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
    default:
      description: Unexpected error
 